language: python

python:
  - "2.7"

install:
  - sudo apt-get update
  - sudo apt-get install inkscape
  - pip install -r scripts/requirements.txt

script:
  - scripts/wws_manage.sh png
  - scripts/wws_manage.sh readmes
